### ISSUE TITLE
Implement Homeassistant autodiscovery

### ISSUE THREAD

**Issue by schrej-zz** [GollmerSt/SolvisSmartHomeServer#12]
Hi,
you already send the config data in a proprietary format (SolvisSmartHomeServer/<devicename>/<ID>
It would be great, if you would (additionally) send the config data in the official Homeassistant format, which is a quasi-standard within Smart Home applications.
They are in the format homeassistant/<devicename>/<ID>/config and a JSON, which corresponds more or less, with your current meta data.
See also eg. at: https://resinchemtech.blogspot.com/2023/12/mqtt-auto-discovery.html
or/and the Youtube video: https://www.youtube.com/watch?v=VHiCtZqllU8

Thanks in advance

**Comment by Fl77777** [comment]
Hi Schrej-zz, have you found a way how to add the SolvisSmartHomeServer in Homeassistant?

**Comment by schrej-zz** [comment]
Hi,
well it's documented in Homeassistant.
I try to implement ist for the value A01:Punpe_Solar.
The configuration has to be sent in a defined manner in the topic e.g.
`homeasistant/sensor/solvis_solvismax6` ,where "sensor" is the type (can be others like binary_sensor, etc. see docs) and solvis_sovismax6 is defined by your own and identifies the device. It should be a retained message.
It's followed by a JSON payload.

```
homeasistant/sensor/pumpe_solar/config
{
    "name": "Solarpumpe",
    "unique_id": "solvis_a01_pumpe_solar",
    "state_topic": "SolvisSmartHomeServer/mySolvis/data/A01:Pumpe_Solar",
    "unit_of_measurement": "%",
    "icon": "mdi:pump",
    "device_class": "None",
    "state_class": "measurement",
    "friendly_name": "Solarpumpe",
    "device": {
        "identifiers": "Solvis_<Seriennummer>",
        "manufacturer": "Solvis",
        "model": "SolvisMax6",
        "name": "SolvisMax",
        "configuration_url": "http://aaa.bbb.ccc.ddd"
    },
    "availability_topic": "SolvisSmartHomeServer/mySolvis/availability/A01:Pumpe_Solar"
}
```
Most of the individual topics are already used by @GollmerSt in his own MQTT configuration topics and can be transfered to the Homeassistant configuration topics.

**Comment by Fl77777** [comment]
Hi, sorry I am completely new to this. Could you maybe point me to some sort of documentation (for dummies) of how to do this? I have read the documentation by GollmerSt several times, however cant find the necessary information of how to integrate it into home assistant. The Solvissmarthomeserver is running, the learning procedure worked and the log file says: "Connection to MQTT successfull" Thank you in advance.

**Comment by schrej-zz** [comment]
OK,
I think, I got you wrong.

You dont want to implement homeassistsnt autodiscovery into the code of @GollmerSt, but just want to integrate it into homeassistant.
Without the aotodiscovery, this is only possible the manual way. (As I did it)
I added each and every item manually into the configuration yaml.

eg. 
```
sensor:
  - name: "I1:Anlagentyp"
    state_topic: "SolvisSmartHomeServer/mySolvis/I1:Anlagentyp/data"
    unique_id: "I1:Anlagentyp"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "I2:Systemnummer"
    state_topic: "SolvisSmartHomeServer/mySolvis/I2:Systemnummer/data"
    unique_id: "I2:Systemnummer"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"

```

**Comment by Fl77777** [comment]
Thank you so much. I got the two examples of you working and the entities are showing up with their respective values. I tried to also add C11:Vorlauf_Soll_HK1 but this entity does not show any data. I looked at the list of all topics using MQTTExplorer and also here some of the topics dont have a data field. Is this normal? C07 for instance is not showing up at all
![MQTTExplorer](https://github.com/user-attachments/assets/3d6af45e-6c58-4d2d-a9a8-b14b79c9428f)

**Comment by schrej-zz** [comment]
Hi,
there is no data field as it is a field, that you can publish ("Soll") and does not come from the solvis.

To ease your (and others) work find enclsed my total code

```
sensor:
  - name: "I1:Anlagentyp"
    state_topic: "SolvisSmartHomeServer/mySolvis/I1:Anlagentyp/data"
    unique_id: "I1:Anlagentyp"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "I2:Systemnummer"
    state_topic: "SolvisSmartHomeServer/mySolvis/I2:Systemnummer/data"
    unique_id: "I2:Systemnummer"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "S01:Warmwasserpuffer"
    state_topic: "SolvisSmartHomeServer/mySolvis/S01:Warmwasserpuffer/data"
    suggested_display_precision: 1
    unit_of_measurement: "°C"
    unique_id: "S01:Warmwasserpuffer"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "S02:Warmwassertemperatur"
    state_topic: "SolvisSmartHomeServer/mySolvis/S02:Warmwassertemperatur/data"
    suggested_display_precision: 1
    unit_of_measurement: "°C"
    unique_id: "S02:Warmwassertemperatur"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "S03:Speicherreferenztemperatur"
    state_topic: "SolvisSmartHomeServer/mySolvis/S03:Speicherreferenztemperatur/data"
    suggested_display_precision: 1
    unit_of_measurement: "°C"
    unique_id: "S03:Speicherreferenztemperatur"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "S04:Heizungspuffertemperatur_oben"
    state_topic: "SolvisSmartHomeServer/mySolvis/S04:Heizungspuffertemperatur_oben/data"
    suggested_display_precision: 1
    unit_of_measurement: "°C"
    unique_id: "S04:Heizungspuffertemperatur_oben"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "S05:Solarvorlauftemperatur"
    state_topic: "SolvisSmartHomeServer/mySolvis/S05:Solarvorlauftemperatur/data"
    suggested_display_precision: 1
    unit_of_measurement: "°C"
    unique_id: "S05:Solarvorlauftemperatur"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "S06:Solarruecklauftemperatur"
    state_topic: "SolvisSmartHomeServer/mySolvis/S06:Solarruecklauftemperatur/data"
    suggested_display_precision: 1
    unit_of_measurement: "°C"
    unique_id: "S06:Solarruecklauftemperatur"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "S07:Solardruck"
    state_topic: "SolvisSmartHomeServer/mySolvis/S07:Solardruck/data"
    suggested_display_precision: 1
    unique_id: "S07:Solardruck"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "S08:Solarkollektortemperatur"
    state_topic: "SolvisSmartHomeServer/mySolvis/S08:Solarkollektortemperatur/data"
    suggested_display_precision: 1
    unit_of_measurement: "°C"
    unique_id: "S08:Solarkollektortemperatur"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "S09:Heizungspuffertemperatur_unten"
    state_topic: "SolvisSmartHomeServer/mySolvis/S09:Heizungspuffertemperatur_unten/data"
    suggested_display_precision: 1
    unit_of_measurement: "°C"
    unique_id: "S09:Heizungspuffertemperatur_unten"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "S10:Aussentemperatur"
    state_topic: "SolvisSmartHomeServer/mySolvis/S10:Aussentemperatur/data"
    suggested_display_precision: 1
    unit_of_measurement: "°C"
    unique_id: "S10:Aussentemperatur"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "S11:ZirkulationRuecklauftemperatur"
    state_topic: "SolvisSmartHomeServer/mySolvis/S11:ZirkulationRuecklauftemperatur/data"
    suggested_display_precision: 1
    unit_of_measurement: "°C"
    unique_id: "S11:ZirkulationRuecklauftemperatur"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "S12:Vorlauftemperatur_HK1"
    state_topic: "SolvisSmartHomeServer/mySolvis/S12:Vorlauftemperatur_HK1/data"
    suggested_display_precision: 1
    unit_of_measurement: "°C"
    unique_id: "S12:Vorlauftemperatur_HK1"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "S13:Vorlauftemperatur_HK2"
    state_topic: "SolvisSmartHomeServer/mySolvis/S13:Vorlauftemperatur_HK2/data"
    suggested_display_precision: 1
    unit_of_measurement: "°C"
    unique_id: "S13:Vorlauftemperatur_HK2"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "S17:Durchfluss_Solarpanel"
    state_topic: "SolvisSmartHomeServer/mySolvis/S17:Durchfluss_Solarpanel/data"
    suggested_display_precision: 1
    unit_of_measurement: "l/h"
    unique_id: "S17:Durchfluss_Solarpanel"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "S18:Durchfluss_Warmwasserzirkulation"
    state_topic: "SolvisSmartHomeServer/mySolvis/S18:Durchfluss_Warmwasserzirkulation/data"
    suggested_display_precision: 1
    unit_of_measurement: "l/h"
    unique_id: "S18:Durchfluss_Warmwasserzirkulation"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "RF1:Raumfuehler_HK1"
    state_topic: "SolvisSmartHomeServer/mySolvis/RF1:Raumfuehler_HK1/data"
    suggested_display_precision: 1
    unit_of_measurement: "°C"
    unique_id: "RF1:Raumfuehler_HK1"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "A01:Pumpe_Solar"
    state_topic: "SolvisSmartHomeServer/mySolvis/A01:Pumpe_Solar/data"
    unique_id: "A01:Pumpe_Solar"
    unit_of_measurement: "%"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "A02:Pumpe_Warmwasser"
    state_topic: "SolvisSmartHomeServer/mySolvis/A02:Pumpe_Warmwasser/data"
    unique_id: "A02:Pumpe_Warmwasser"
    unit_of_measurement: "%"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "A03:Pumpe_HK1"
    state_topic: "SolvisSmartHomeServer/mySolvis/A03:Pumpe_HK1/data"
    unique_id: "A03:Pumpe_HK1"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "A05:Pumpe_Warmwasserzirkulation"
    state_topic: "SolvisSmartHomeServer/mySolvis/A05:Pumpe_Warmwasserzirkulation/data"
    unique_id: "A05:Pumpe_Warmwasserzirkulation"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "A08:Mischer_HK1_auf"
    state_topic: "SolvisSmartHomeServer/mySolvis/A08:Mischer_HK1_auf/data"
    unique_id: "A08:Mischer_HK1_auf"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "A09:Mischer_HK1_zu"
    state_topic: "SolvisSmartHomeServer/mySolvis/A09:Mischer_HK1_zu/data"
    unique_id: "A09:Mischer_HK1_zu"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "A12:Brenner"
    state_topic: "SolvisSmartHomeServer/mySolvis/A12:Brenner/data"
    unique_id: "A12:Brenner"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "A14:Entstoerung"
    state_topic: "SolvisSmartHomeServer/mySolvis/A14:Entstoerung/data"
    unique_id: "A14:Entstoerung"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "SE:Solarertrag_kWh"
    state_topic: "SolvisSmartHomeServer/mySolvis/SE:Solarertrag_kWh/data"
    unique_id: "SE:Solarertrag_kWh"
    unit_of_measurement: "kWh"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "SL:Solarleistung_kW"
    state_topic: "SolvisSmartHomeServer/mySolvis/SL:Solarleistung_kW/data"
    unique_id: "SL:Solarleistung_kW"
    unit_of_measurement: "kW"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "X01:BrennerStarts"
    state_topic: "SolvisSmartHomeServer/mySolvis/X01:BrennerStarts/data"
    unique_id: "X01:BrennerStarts"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "X02:BrennerLaufzeit_s"
    state_topic: "SolvisSmartHomeServer/mySolvis/X02:BrennerLaufzeit_s/data"
    unique_id: "X02:BrennerLaufzeit_s"
    unit_of_measurement: "s"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "X05:BrennerStatus"
    state_topic: "SolvisSmartHomeServer/mySolvis/X05:BrennerStatus/data"
    unique_id: "X05:BrennerStatus"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "X06:UhrzeitSolvis"
    state_topic: "SolvisSmartHomeServer/mySolvis/X06:UhrzeitSolvis/data"
    unique_id: "X06:UhrzeitSolvis"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "X07:MischerPosition0_HK1"
    state_topic: "SolvisSmartHomeServer/mySolvis/X07:MischerPosition0_HK1/data"
    unique_id: "X07:MischerPosition0_HK1"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "X09:LaufzeitSolarpumpe_s"
    state_topic: "SolvisSmartHomeServer/mySolvis/X09:LaufzeitSolarpumpe_s/data"
    unique_id: "X09:LaufzeitSolarpumpe_s"
    unit_of_measurement: "s"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "C01:StartsBrenner"
    state_topic: "SolvisSmartHomeServer/mySolvis/C01:StartsBrenner/data"
    unique_id: "C01:StartsBrenner"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "C02:LaufzeitBrenner"
    state_topic: "SolvisSmartHomeServer/mySolvis/C02:LaufzeitBrenner/data"
    unique_id: "C02:LaufzeitBrenner"
    unit_of_measurement: "h"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "C05:WassertemperaturSoll"
    state_topic: "SolvisSmartHomeServer/mySolvis/C05:WassertemperaturSoll/data"
    suggested_display_precision: 1
    unit_of_measurement: "°C"
    unique_id: "C05:WassertemperaturSoll"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "C06:Anlagenmodus_HK1"
    state_topic: "SolvisSmartHomeServer/mySolvis/C06:Anlagenmodus_HK1/data"
    unique_id: "C06:Anlagenmodus_HK1"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "C07:Tagestemperatur_HK1"
    state_topic: "SolvisSmartHomeServer/mySolvis/C07:Tagestemperatur_HK1/data"
    suggested_display_precision: 1
    unit_of_measurement: "°C"
    unique_id: "C07:Tagestemperatur_HK1"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "C08:Nachttemperatur_HK1"
    state_topic: "SolvisSmartHomeServer/mySolvis/C08:Nachttemperatur_HK1/data"
    suggested_display_precision: 1
    unit_of_measurement: "°C"
    unique_id: "C08:Nachttemperatur_HK1"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "C09:TemperaturFeineinstellung_HK1"
    state_topic: "SolvisSmartHomeServer/mySolvis/C09:TemperaturFeineinstellung_HK1/data"
    suggested_display_precision: 1
    unique_id: "C09:TemperaturFeineinstellung_HK1"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "C10:Raumeinfluss_HK1"
    state_topic: "SolvisSmartHomeServer/mySolvis/C10:Raumeinfluss_HK1/data"
    suggested_display_precision: 1
    unit_of_measurement: "%"
    unique_id: "C10:Raumeinfluss_HK1"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "C11:Vorlauf_Soll_HK1"
    state_topic: "SolvisSmartHomeServer/mySolvis/C11:Vorlauf_Soll_HK1/data"
    suggested_display_precision: 1
    unit_of_measurement: "°C"
    unique_id: "C11:Vorlauf_Soll_HK1"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "C24:LaufzeitSolarpumpe"
    state_topic: "SolvisSmartHomeServer/mySolvis/C24:LaufzeitSolarpumpe/data"
    suggested_display_precision: 1
    unit_of_measurement: "h"
    unique_id: "C24:LaufzeitSolarpumpe"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "C26:Warmwasserzirkulation_Puls"
    state_topic: "SolvisSmartHomeServer/mySolvis/C26:Warmwasserzirkulation_Puls/data"
    unique_id: "C26:Warmwasserzirkulation_Puls"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "C27:Warmwasserzirkulation_Zeit"
    state_topic: "SolvisSmartHomeServer/mySolvis/C27:Warmwasserzirkulation_Zeit/data"
#    suggested_display_precision: 1
    unique_id: "C27:Warmwasserzirkulation_Zeit"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "C28:WW_Pumpe_Min_Laufzeit"
    state_topic: "SolvisSmartHomeServer/mySolvis/C28:WW_Pumpe_Min_Laufzeit/data"
    suggested_display_precision: 1
    unit_of_measurement: "s"
    unique_id: "C28:WW_Pumpe_Min_Laufzeit"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "C29:BetriebsartVT_HK1"
    state_topic: "SolvisSmartHomeServer/mySolvis/C29:BetriebsartVT_HK1/data"
    suggested_display_precision: 1
    unique_id: "C29:BetriebsartVT_HK1"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "C30:Steilheit_HK1"
    state_topic: "SolvisSmartHomeServer/mySolvis/C30:Steilheit_HK1/data"
    suggested_display_precision: 1
    unique_id: "C30:Steilheit_HK1"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "C31:Fix_Vorlauf_Tag_HK1"
    state_topic: "SolvisSmartHomeServer/mySolvis/C31:Fix_Vorlauf_Tag_HK1/data"
    suggested_display_precision: 1
    unit_of_measurement: "°C"
    unique_id: "C31:Fix_Vorlauf_Tag_HK1"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "C32:Fix_Vorlauf_Absenk_HK1"
    state_topic: "SolvisSmartHomeServer/mySolvis/C32:Fix_Vorlauf_Absenk_HK1/data"
    suggested_display_precision: 1
    unit_of_measurement: "°C"
    unique_id: "C32:Fix_Vorlauf_Absenk_HK1"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"
  - name: "C33:Min_Vorlauf_Temp_HK1"
    state_topic: "SolvisSmartHomeServer/mySolvis/C33:Min_Vorlauf_Temp_HK1/data"
    suggested_display_precision: 1
    unit_of_measurement: "°C"
    unique_id: "C33:Min_Vorlauf_Temp_HK1"
    device:
      name: "SolvisMax6"
      manufacturer: "Solvis"
      model: "SolvisMax6"
      identifiers:
        - "26"

```

**Comment by Fl77777** [comment]
Hi, Thank you so much, the code helps a lot and saves me a lot of time. About C11 being a publishable (Soll) value I am not sure as it says writeable "false" in the metadata of C11. This is what I actually would like to do using home assistant, namely to adjust the "Vorlauftemperatur" of the individual "Heizkreise". This could e.g. be done by adjusting C09 "TemperaturFeineinstellung" however the entity is configured as sensor so i does not let me alter it. Do you succesfully control your Solvis heating using the SolvisSmarthomeServer? Sorry to be a pain with all these questions.

**Comment by schrej-zz** [comment]
For publishing you have to either define the command topic or use the mqtt publish option in the action of an automation

**Comment by Fl77777** [comment]
Do you by any chance have a code snippet of how you implemented it with your heating? Thank you im advance

**Comment by schrej-zz** [comment]
No,
but it should be an easy one using automation via UI.
If x then mqtt_publish(topic, payload)

**Comment by tloebhard** [comment]
Hi,
I'm also using this very useful interface with Home Assistant since a year - regarding controlling of C* topics I use mqtt number instead mqtt sensor:

```yaml
- command_topic: "SolvisSmartHomeServer/homeAssistant/mySolvis/C09:TemperaturFeineinstellung_HK1/cmnd"
  unique_id: solvis_hk1_feineinstellung
  name: "HK1 Feineinstellung"
  state_topic: "SolvisSmartHomeServer/mySolvis/C09:TemperaturFeineinstellung_HK1/data"
  min: -5
  max: 5
  unit_of_measurement: K
- command_topic: "SolvisSmartHomeServer/homeAssistant/mySolvis/C15:TemperaturFeineinstellung_HK2/cmnd"
  unique_id: solvis_hk2_feineinstellung
  name: "HK2 Feineinstellung"
  state_topic: "SolvisSmartHomeServer/mySolvis/C15:TemperaturFeineinstellung_HK2/data"
  min: -5
  max: 5
  unit_of_measurement: K
```


For X* topics I use binary_sensor:
```yaml
- unique_id: solvis_hk1_mischer_auf
  name: "HK1 Mischer auf"
  state_topic: "SolvisSmartHomeServer/mySolvis/A08:Mischer_HK1_auf/data"
  payload_on: "true"
  payload_off: "false"
- unique_id: solvis_hk1_mischer_zu
  name: "HK1 Mischer zu"
  state_topic: "SolvisSmartHomeServer/mySolvis/A09:Mischer_HK1_zu/data"
  payload_on: "true"
  payload_off: "false"
- unique_id: solvis_hk1_pumpe
  name: "HK1 Pumpe"
  state_topic: "SolvisSmartHomeServer/mySolvis/A03:Pumpe_HK1/data"
  payload_on: "true"
  payload_off: "false"
- unique_id: solvis_hk2_mischer_auf
  name: "HK2 Mischer auf"
  state_topic: "SolvisSmartHomeServer/mySolvis/A10:Mischer_HK2_auf/data"
  payload_on: "true"
  payload_off: "false"
- unique_id: solvis_hk2_mischer_zu
  name: "HK2 Mischer zu"
  state_topic: "SolvisSmartHomeServer/mySolvis/A11:Mischer_HK2_zu/data"
  payload_on: "true"
  payload_off: "false"
- unique_id: solvis_hk2_pumpe
  name: "HK2 Pumpe"
  state_topic: "SolvisSmartHomeServer/mySolvis/A04:Pumpe_HK2/data"
  payload_on: "true"
  payload_off: "false"
- unique_id: solvis_zirkulation_pumpe
  name: "Zirkulation Pumpe"
  state_topic: "SolvisSmartHomeServer/mySolvis/A05:Pumpe_Warmwasserzirkulation/data"
  payload_on: "true"
  payload_off: "false"
- unique_id: solvis_brenner
  name: "Brenner"
  state_topic: "SolvisSmartHomeServer/mySolvis/A12:Brenner/data"
  payload_on: "true"
  payload_off: "false"
- unique_id: solvis_holzkessel_ladepumpe
  name: "Holzkessel Ladepumpe"
  state_topic: "SolvisSmartHomeServer/mySolvis/A13:Ladepumpe/data"
  payload_on: "true"
  payload_off: "false"
```

For setting the heating I use climate - that's not completely correct but I liked the interface: (you could also use mqtt select for selecting mode)
```yaml
- unique_id: solvis_hk1
  name: "HK1"
  modes:
    - "auto"
    - "off"
    - "heat"
  mode_command_topic: "SolvisSmartHomeServer/homeAssistant/mySolvis/C06:Anlagenmodus_HK1/cmnd"
  mode_command_template: "{{ 'Tag' if value=='heat' else 'Nacht' if value=='off' else 'Timer' }}"
  mode_state_topic: "SolvisSmartHomeServer/mySolvis/C06:Anlagenmodus_HK1/data"
  mode_state_template: "{{ 'heat' if value=='Tag' else 'auto' if value=='Timer' else 'off' }}"
  current_temperature_topic: "SolvisSmartHomeServer/mySolvis/S12:Vorlauftemperatur_HK1/data"
  temperature_state_topic: "SolvisSmartHomeServer/mySolvis/C11:Vorlauf_Soll_HK1/data" 
  temperature_unit: "C"
  precision: 0.1
  min_temp: 0
  max_temp: 60
- unique_id: solvis_hk2
  name: "HK2"
  modes:
    - "auto"
    - "off"
    - "heat"
  mode_command_topic: "SolvisSmartHomeServer/homeAssistant/mySolvis/C12:Anlagenmodus_HK2/cmnd"
  mode_command_template: "{{ 'Tag' if value=='heat' else 'Nacht' if value=='off' else 'Timer' }}"
  mode_state_topic: "SolvisSmartHomeServer/mySolvis/C12:Anlagenmodus_HK2/data"
  mode_state_template: "{{ 'heat' if value=='Tag' else 'auto' if value=='Timer' else 'off' }}"
  current_temperature_topic: "SolvisSmartHomeServer/mySolvis/S13:Vorlauftemperatur_HK2/data"
  temperature_state_topic: "SolvisSmartHomeServer/mySolvis/C17:Vorlauf_Soll_HK2/data" 
  temperature_unit: "C"
  precision: 0.1
  min_temp: 0
  max_temp: 40
```

For switching circulation on/off - mqtt switch:

```yaml
- unique_id: solvis_zirkulation_puls
  name: "Zirkulation Puls"
  state_topic: "SolvisSmartHomeServer/mySolvis/C26:Warmwasserzirkulation_Puls/data"
  command_topic: "SolvisSmartHomeServer/homeAssistant/mySolvis/C26:Warmwasserzirkulation_Puls/cmnd"
  payload_on: "true"
  payload_off: "false"
  state_on: "true"
  state_off: "false"
- unique_id: solvis_zirkulation_zeit
  name: "Zirkulation Zeit"
  state_topic: "SolvisSmartHomeServer/mySolvis/C27:Warmwasserzirkulation_Zeit/data"
  command_topic: "SolvisSmartHomeServer/homeAssistant/mySolvis/C27:Warmwasserzirkulation_Zeit/cmnd"
  payload_on: "true"
  payload_off: "false"
  state_on: "true"
  state_off: "false"
```

mqtt buttons for just clicks:
```yaml
- unique_id: solvis_hk1_vl_soll_update
  name: "HK1 VL SOLL aktualisieren"
  command_topic: "SolvisSmartHomeServer/homeAssistant/mySolvis/C11:Vorlauf_Soll_HK1/update"
- unique_id: solvis_channels_update
  name: "Alle Solvis Kanäle aktualisieren"
  command_topic: "SolvisSmartHomeServer/homeAssistant/mySolvis/server/cmnd"
  payload_press: "UPDATE_CHANNELS"
- unique_id: solvis_goto_admin
  name: "In Installateursmodus gehen"
  command_topic: "SolvisSmartHomeServer/homeAssistant/mySolvis/screen/cmnd"
  payload_press: "Installateur-Menue"
- unique_id: solvis_goto_none
  name: "Auf initial gehen"
  command_topic: "SolvisSmartHomeServer/homeAssistant/mySolvis/screen/cmnd"
  payload_press: "NONE"
- unique_id: solvis_warmwasser_nachheizen
  name: "Warmwasser nachheizen"
  command_topic: "SolvisSmartHomeServer/homeAssistant/mySolvis/C46:WarmwasserNachheizen/cmnd"
  payload_press: "heating"
```

...and finally, mqtt water_heater: (same as for climate - not perfect but I liked it)
```yaml
- unique_id: solvis_warmwasser
  name: "Warmwasser"
  temperature_state_topic: "SolvisSmartHomeServer/mySolvis/C05:WassertemperaturSoll/data"
  temperature_command_topic: "SolvisSmartHomeServer/homeAssistant/mySolvis/C05:WassertemperaturSoll/cmnd"
  current_temperature_topic: "SolvisSmartHomeServer/mySolvis/S02:Warmwassertemperatur/data"
  modes:
    - "off"
    - "eco"
  mode_command_topic: "SolvisSmartHomeServer/homeAssistant/mySolvis/C04:WarmwasserPumpe/cmnd"
  mode_command_template: "{{ 'aus' if value=='off' else 'auto' }}"
  mode_state_topic: "SolvisSmartHomeServer/mySolvis/C04:WarmwasserPumpe/data"
  mode_state_template: "{{ 'off' if value=='aus' else 'eco' }}"
  precision: 0.1
  min_temp: 10
```
