### ISSUE TITLE
Add installation instructions for Home Assistant (OS, on Raspberry Pi) or even let it install as addon

### ISSUE THREAD

**Issue by tloebhard** [GollmerSt/SolvisSmartHomeServer#15]
Hi,

I'm running SolvisSmartHomeServer on Home Assistant OS on a Raspberry Pi 5 since a year as addon, it works very well and maybe someone else wants to let it run in Home Assistant.

After you know how to [make an addon](https://developers.home-assistant.io/docs/add-ons/) - it's quite easy:

Next to `SolvisSmartHomeServer.jar` and `base.xml` you need following files:

`config.yaml`
```yaml
name: "SolvisSmartHomeServer"
description: "https://github.com/GollmerSt/SolvisSmartHomeServer"
version: "1.0.2"
slug: "solvis_smart_home_server"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
```

`Dockerfile`
```Dockerfile
ARG BUILD_FROM
FROM $BUILD_FROM

# install openjdk
RUN apk add openjdk11

# Copy data for add-on
COPY run.sh /
RUN chmod a+x /run.sh

COPY SolvisSmartHomeServer.jar /
COPY base.xml /

CMD [ "/run.sh" ]
```

`run.sh`
```Shell
#!/usr/bin/with-contenv bashio

echo "Starting SolvisSmartHomeServer"

java -jar SolvisSmartHomeServer.jar
```

...and put all the five files in `/addons/solvis_smart_home_server`. Then you can install it from "Local add-ons" on "Add-on Store" in Home Assistant.

Maybe this repository could also be made to a Home Assistant Addon repository - but I'm currently not into that. And you could also let Home Assistant generate your `base.xml` using the GUI configuration of an addon - but for me it was fine doing it in the file, as you usually just once set the settings.

Have fun - and thank you for that great Solvis interface!
